---
layout: cv
title: Yodahe Mulugeta's CV
---
# Yodahe Mulugeta


<div id="webaddress">
<a href="linkedin.com/in/yodahe-mulugeta-yodahe">My linkedin page</a>
| <a href="https://github.com/Yodahe-M/
Yodahe-M
">My github page</a>
</div>


## Education
##### BS, Computer Science
- GPA - 3.95
- Emphasis in Functional Programming
- Computer Science social media President | BYU-I Computing Society
- Computer Science Society Secretary | BYU-I Computing Society
- Brigham Young University - Idaho Scholarship

## Work Experience
##### Online Computer Science Tutor
- Provided guidance to students in computer science, emphasizing beginning Python and SQL, fostering enhanced proficiency and understanding of fundamental concepts in programming
- Directed students in addressing and resolving technical challenges, leading to a 15% increase in overall grades
- Clarified technical concepts weekly for over 10 students with diverse experience levels

##### Computing Society Social Media President
- Designed visually captivating flyers for weekly Computing Society activities, incorporating event 
details, resulting in a 20% increase in event attendance
- Executed a comprehensive communication strategy by distributing flyers, emailing event 
announcements, and promoting on social media platforms resulting in a 30% increase in audience 
reach and awareness of Computing Society events

##### Computing Society Secretary

- Developed tailored meeting agendas for the Computing Society, outlining specific discussion topics, 
deadlines, and assigned responsibilities for each member of presidency
- Assigned clear tasks to each member of the Computing Society presidency following meetings, 
ensuring accountability and progress on key action items

## Skills
- Programming Languages: Python, C#, MySQL
- Tools: Git, GitHub, visual studio, vs code
- Soft skills: Teamwork, Critical Thinking, Problem solvin


<!-- ### Footer

Last updated: May 2013 -->